In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

In [21]:
bitcoin = yf.download(
    "BTC-USD",
    start="2020-01-01",
    end="2026-01-01",
    auto_adjust=False
)

[*********************100%***********************]  1 of 1 completed

In [24]:
bitcoin.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,,
2020-01-01,7200.174316,7200.174316,7254.330566,7174.944336,7194.892090,18565664997
2020-01-02,6985.470215,6985.470215,7212.155273,6935.270020,7202.551270,20802083465
2020-01-03,7344.884277,7344.884277,7413.715332,6914.996094,6984.428711,28111481032
2020-01-04,7410.656738,7410.656738,7427.385742,7309.514160,7345.375488,18444271275
2020-01-05,7411.317383,7411.317383,7544.497070,7400.535645,7410.451660,19725074095

In [26]:
ethereum = yf.download(
    "ETH-USD",
    start="2020-01-01",
    end="2026-01-01",
    auto_adjust=False
)

[*********************100%***********************]  1 of 1 completed

In [28]:
ethereum.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,ETH-USD,ETH-USD,ETH-USD,ETH-USD,ETH-USD,ETH-USD
Date,,,,,,
2020-01-01,130.802002,130.802002,132.835358,129.198288,129.630661,7935230330
2020-01-02,127.410179,127.410179,130.820038,126.954910,130.820038,8032709256
2020-01-03,134.171707,134.171707,134.554016,126.490021,127.411263,10476845358
2020-01-04,135.069366,135.069366,136.052719,133.040558,134.168518,7430904515
2020-01-05,136.276779,136.276779,139.410202,135.045624,135.072098,7526675353

In [30]:
bitcoin = bitcoin[["Close"]].copy()
ethereum = ethereum[["Close"]].copy()

In [32]:
bitcoin.columns = ["BTC_Close"]
ethereum.columns = ["ETH_Close"]

In [34]:
bitcoin.head()

              BTC_Close
Date
2020-01-01  7200.174316
2020-01-02  6985.470215
2020-01-03  7344.884277
2020-01-04  7410.656738
2020-01-05  7411.317383

In [36]:
ethereum.head()

             ETH_Close
Date
2020-01-01  130.802002
2020-01-02  127.410179
2020-01-03  134.171707
2020-01-04  135.069366
2020-01-05  136.276779

In [38]:
dados = bitcoin.join(ethereum, how="inner") #junta as duas tabelas

In [40]:
dados.head()

              BTC_Close   ETH_Close
Date
2020-01-01  7200.174316  130.802002
2020-01-02  6985.470215  127.410179
2020-01-03  7344.884277  134.171707
2020-01-04  7410.656738  135.069366
2020-01-05  7411.317383  136.276779

In [42]:
dados["Target"] = (
    dados["BTC_Close"].shift(-1) > dados["BTC_Close"]
).astype(int)

#cria o target -> 0 para não; 1 para sim
#0 -> o preço de amanha nao vai ser maior que o de hoje
#1 -> o preço de amanhã vai ser maior que o de hoje

In [44]:
dados.head(10)

              BTC_Close   ETH_Close  Target
Date
2020-01-01  7200.174316  130.802002       0
2020-01-02  6985.470215  127.410179       1
2020-01-03  7344.884277  134.171707       1
2020-01-04  7410.656738  135.069366       1
2020-01-05  7411.317383  136.276779       1
2020-01-06  7769.219238  144.304153       1
2020-01-07  8163.692383  143.543991       0
2020-01-08  8079.862793  141.258133       0
2020-01-09  7879.071289  138.979202       1
2020-01-10  8166.554199  143.963776       0

In [46]:
dados = dados.dropna()

In [48]:
dados.tail()

               BTC_Close    ETH_Close  Target
Date
2025-12-27  87802.156250  2947.998291       1
2025-12-28  87835.835938  2948.568115       0
2025-12-29  87138.140625  2934.538330       1
2025-12-30  88430.132812  2971.416748       0
2025-12-31  87508.828125  2967.037598       0

In [50]:
dados["BTC_Lag1"] = dados["BTC_Close"].shift(1) #preço do Bitcoin um dia atrás

In [52]:
dados.head()

              BTC_Close   ETH_Close  Target     BTC_Lag1
Date
2020-01-01  7200.174316  130.802002       0          NaN
2020-01-02  6985.470215  127.410179       1  7200.174316
2020-01-03  7344.884277  134.171707       1  6985.470215
2020-01-04  7410.656738  135.069366       1  7344.884277
2020-01-05  7411.317383  136.276779       1  7410.656738

In [54]:
for lag in range(1, 8):
    dados[f"BTC_Lag{lag}"] = dados["BTC_Close"].shift(lag)

#cria 7 lags, no qual mostra os preços dos dias, ex: lag 2 -> preço do Bitcoin 2 dias atrás

In [56]:
for lag in range(1, 8):
    dados[f"ETH_Lag{lag}"] = dados["ETH_Close"].shift(lag)

#cria 7 lags, no qual mostra os preços dos dias, ex: lag 2 -> preço do Ethereum 2 dias atrás

In [58]:
dados = dados.dropna()
#remover linhas incompletas

In [60]:
dados.head() #mostrar a tabela

,BTC_Close,ETH_Close,Target,BTC_Lag1,BTC_Lag2,BTC_Lag3,BTC_Lag4,BTC_Lag5,BTC_Lag6,BTC_Lag7,ETH_Lag1,ETH_Lag2,ETH_Lag3,ETH_Lag4,ETH_Lag5,ETH_Lag6,ETH_Lag7
Date,,,,,,,,,,,,,,,,,
2020-01-08,8079.862793,141.258133,0,8163.692383,7769.219238,7411.317383,7410.656738,7344.884277,6985.470215,7200.174316,143.543991,144.304153,136.276779,135.069366,134.171707,127.410179,130.802002
2020-01-09,7879.071289,138.979202,1,8079.862793,8163.692383,7769.219238,7411.317383,7410.656738,7344.884277,6985.470215,141.258133,143.543991,144.304153,136.276779,135.069366,134.171707,127.410179
2020-01-10,8166.554199,143.963776,0,7879.071289,8079.862793,8163.692383,7769.219238,7411.317383,7410.656738,7344.884277,138.979202,141.258133,143.543991,144.304153,136.276779,135.069366,134.171707
2020-01-11,8037.537598,142.927109,1,8166.554199,7879.071289,8079.862793,8163.692383,7769.219238,7411.317383,7410.656738,143.963776,138.979202,141.258133,143.543991,144.304153,136.276779,135.069366
2020-01-12,8192.494141,145.873932,0,8037.537598,8166.554199,7879.071289,8079.862793,8163.692383,7769.219238,7411.317383,142.927109,143.963776,138.979202,141.258133,143.543991,144.304153,136.276779

In [62]:
dados.columns #mostrar o nome das colunas

#a ideia é usar os dados do passado e não do futuro

Index(['BTC_Close', 'ETH_Close', 'Target', 'BTC_Lag1', 'BTC_Lag2', 'BTC_Lag3',
       'BTC_Lag4', 'BTC_Lag5', 'BTC_Lag6', 'BTC_Lag7', 'ETH_Lag1', 'ETH_Lag2',
       'ETH_Lag3', 'ETH_Lag4', 'ETH_Lag5', 'ETH_Lag6', 'ETH_Lag7'],
      dtype='str')

In [64]:
def calcular_wma(serie, periodo):
    pesos = np.arange(1, periodo + 1)
    
    wma = serie.rolling(periodo).apply(
        lambda valores: np.dot(valores, pesos) / pesos.sum(),
        raw=True
    )
    
    return wma

#a função wma é uma média dos preços anteriores, mas os dias mais recentes recebem mais peso, visto que o dia mais próximo influecia mais na media 
# na nossa ideia, vamos usar um intervalo de 30 dias

In [66]:
dados["BTC_WMA30"] = calcular_wma(
    dados["BTC_Close"],
    30 #30 dias 
)

In [68]:
dados["ETH_WMA30"] = calcular_wma(
    dados["ETH_Close"],
    30
)

In [70]:
dados = dados.dropna() #remover as linhas incompletas, visto que os primeiros 29 dias não conseguem ter uma WMA30 completa.

In [72]:
dados.head()

,BTC_Close,ETH_Close,Target,BTC_Lag1,BTC_Lag2,BTC_Lag3,BTC_Lag4,BTC_Lag5,BTC_Lag6,BTC_Lag7,ETH_Lag1,ETH_Lag2,ETH_Lag3,ETH_Lag4,ETH_Lag5,ETH_Lag6,ETH_Lag7,BTC_WMA30,ETH_WMA30
Date,,,,,,,,,,,,,,,,,,,
2020-02-06,9729.801758,212.339081,1,9613.423828,9180.962891,9293.521484,9344.365234,9392.875000,9350.529297,9508.993164,204.230240,189.250595,189.865067,188.617538,183.673950,180.160172,184.690475,9053.165165,178.357966
2020-02-07,9795.943359,222.726059,1,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,9392.875000,9350.529297,212.339081,204.230240,189.250595,189.865067,188.617538,183.673950,180.160172,9116.695015,181.797169
2020-02-08,9865.119141,223.146515,1,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,9392.875000,222.726059,212.339081,204.230240,189.250595,189.865067,188.617538,183.673950,9180.997323,185.088298
2020-02-09,10116.673828,228.578568,0,9865.119141,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,223.146515,222.726059,212.339081,204.230240,189.250595,189.865067,188.617538,9257.257895,188.548877
2020-02-10,9856.611328,223.522705,1,10116.673828,9865.119141,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,228.578568,223.146515,222.726059,212.339081,204.230240,189.250595,189.865067,9312.546436,191.501304

In [74]:
dados.columns

Index(['BTC_Close', 'ETH_Close', 'Target', 'BTC_Lag1', 'BTC_Lag2', 'BTC_Lag3',
       'BTC_Lag4', 'BTC_Lag5', 'BTC_Lag6', 'BTC_Lag7', 'ETH_Lag1', 'ETH_Lag2',
       'ETH_Lag3', 'ETH_Lag4', 'ETH_Lag5', 'ETH_Lag6', 'ETH_Lag7', 'BTC_WMA30',
       'ETH_WMA30'],
      dtype='str')

In [76]:
colunas_features = [
    "BTC_Close",
    "BTC_Lag1",
    "BTC_Lag2",
    "BTC_Lag3",
    "BTC_Lag4",
    "BTC_Lag5",
    "BTC_Lag6",
    "BTC_Lag7",
    "BTC_WMA30",
    "ETH_Close",
    "ETH_Lag1",
    "ETH_Lag2",
    "ETH_Lag3",
    "ETH_Lag4",
    "ETH_Lag5",
    "ETH_Lag6",
    "ETH_Lag7",
    "ETH_WMA30"
]

dados = dados[colunas_features + ["Target"]]
#deixar o target no final para ficar mais "bonito" e mais intuitivo

In [78]:
dados.columns

Index(['BTC_Close', 'BTC_Lag1', 'BTC_Lag2', 'BTC_Lag3', 'BTC_Lag4', 'BTC_Lag5',
       'BTC_Lag6', 'BTC_Lag7', 'BTC_WMA30', 'ETH_Close', 'ETH_Lag1',
       'ETH_Lag2', 'ETH_Lag3', 'ETH_Lag4', 'ETH_Lag5', 'ETH_Lag6', 'ETH_Lag7',
       'ETH_WMA30', 'Target'],
      dtype='str')

In [80]:
#Tudo antes de Target são as features
#X = atributos que o modelo pode usar
#y = aquilo que queremos prever

X = dados.drop(columns=["Target"]) #ele pega todas as colunas de dados, menos o Target
y = dados["Target"] #ele pega apenas a coluna target (que é o qe nos queremos prever)

In [82]:
y.head(10)

Date
2020-02-06    1
2020-02-07    1
2020-02-08    1
2020-02-09    0
2020-02-10    1
2020-02-11    1
2020-02-12    0
2020-02-13    1
2020-02-14    0
2020-02-15    1
Name: Target, dtype: int64

In [84]:
X.head()

,BTC_Close,BTC_Lag1,BTC_Lag2,BTC_Lag3,BTC_Lag4,BTC_Lag5,BTC_Lag6,BTC_Lag7,BTC_WMA30,ETH_Close,ETH_Lag1,ETH_Lag2,ETH_Lag3,ETH_Lag4,ETH_Lag5,ETH_Lag6,ETH_Lag7,ETH_WMA30
Date,,,,,,,,,,,,,,,,,,
2020-02-06,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,9392.875000,9350.529297,9508.993164,9053.165165,212.339081,204.230240,189.250595,189.865067,188.617538,183.673950,180.160172,184.690475,178.357966
2020-02-07,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,9392.875000,9350.529297,9116.695015,222.726059,212.339081,204.230240,189.250595,189.865067,188.617538,183.673950,180.160172,181.797169
2020-02-08,9865.119141,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,9392.875000,9180.997323,223.146515,222.726059,212.339081,204.230240,189.250595,189.865067,188.617538,183.673950,185.088298
2020-02-09,10116.673828,9865.119141,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,9344.365234,9257.257895,228.578568,223.146515,222.726059,212.339081,204.230240,189.250595,189.865067,188.617538,188.548877
2020-02-10,9856.611328,10116.673828,9865.119141,9795.943359,9729.801758,9613.423828,9180.962891,9293.521484,9312.546436,223.522705,228.578568,223.146515,222.726059,212.339081,204.230240,189.250595,189.865067,191.501304

In [86]:
total_linhas = len(X)

print("Total de linhas:", total_linhas)

Total de linhas: 2156

In [88]:
indice_divisao = int(total_linhas * 0.8) #80% treino

print("Índice da divisão:", indice_divisao)

Índice da divisão: 1724

In [90]:
X_treino = X.iloc[:indice_divisao] #pega do começo ate a divisao
X_teste = X.iloc[indice_divisao:] #pega da divisao ate o final 

y_treino = y.iloc[:indice_divisao]
y_teste = y.iloc[indice_divisao:]

In [92]:
print("X treino:", X_treino.shape) #(qntdd de linhas, qntdd de features que criamos)
print("X teste:", X_teste.shape)
print("y treino:", y_treino.shape)
print("y teste:", y_teste.shape)


#LEMBRAR: feature (atributo) é uma informação que entregamos ao modelo para ele usar na hora de fazer uma previsão.
#LEMBRAR: SVM - É um algoritmo de Machine Learning supervisionado usado principalmente para classificação.
#A SVM vai aprender, a partir dos dados históricos de Bitcoin e Ethereum, a classificar se o Bitcoin terá alta (1) ou não (0) no dia seguinte.
#nossas features são o preço de fechamento + as lags (preços anteriores) + WMA (as medias dos 30 dias anteriores com peso maior nos valores mais recentes)

X treino: (1724, 18)
X teste: (432, 18)
y treino: (1724,)
y teste: (432,)

In [94]:
from sklearn.preprocessing import StandardScaler #serve para colocar as features em uma escala parecida

In [96]:
escalador = StandardScaler()

In [104]:
X_treino_escalado = escalador.fit_transform(X_treino)
X_teste_escalado = escalador.transform(X_teste)
#Dados de treino: fit_transform()
#Dados de teste: transform()

In [107]:
print("Formato do treino:", X_treino_escalado.shape) #1724 diaspara treinar a SVM com 18 features cada dia
print("Formato do teste:", X_teste_escalado.shape) #432 dias para testar com 18 features cada dia

Formato do treino: (1724, 18)
Formato do teste: (432, 18)

In [108]:
#A SVM é o algoritmo que vamos treinar para aprender 
# a classificar cada exemplo como 0 (Bitcoin não subiu) 
# ou 1 (Bitcoin subiu), usando as informações históricas de Bitcoin e Ethereum.

In [109]:
from sklearn.svm import SVC

In [112]:
modelo_svm = SVC( # "modelo_svm": variável que vai guardar nosso modelo SVM
    kernel="rbf",
    probability=True, #probabilidades associadas às classes
    random_state=42 #tornar determinados procedimentos internos reprodutíveis
)

In [115]:
modelo_svm.fit(X_treino_escalado, y_treino) #fit: "aprenda a partir desses dados."

C:\Users\victo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVC(probability=True, random_state=42)

In [117]:
previsoes = modelo_svm.predict(X_teste_escalado)

In [118]:
print(previsoes[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [123]:
print("Quantidade de previsões 0:", (previsoes == 0).sum())
print("Quantidade de previsões 1:", (previsoes == 1).sum()) #tem algo errado kkkk
print("Valores reais:")
print(y_teste.value_counts())

Quantidade de previsões 0: 432
Quantidade de previsões 1: 0
Valores reais:
Target
1    218
0    214
Name: count, dtype: int64

In [125]:
previsoes_treino = modelo_svm.predict(X_treino_escalado)

In [128]:
print("Previsões no treino:")
print("Classe 0:", (previsoes_treino == 0).sum())
print("Classe 1:", (previsoes_treino == 1).sum())
print("Valores reais do treino:")
print(y_treino.value_counts())

Previsões no treino:
Classe 0: 811
Classe 1: 913
Valores reais do treino:
Target
1    880
0    844
Name: count, dtype: int64

In [129]:
print("Média do treino:")
print(X_treino_escalado.mean(axis=0))

print("\nMédia do teste:")
print(X_teste_escalado.mean(axis=0))

Média do treino:
[ 9.89154621e-17 -1.64859103e-16 -3.29718207e-17 -1.97830924e-16
  1.15401372e-16 -1.48373193e-16  1.64859103e-16  0.00000000e+00
  1.81345014e-16 -4.94577310e-17 -3.29718207e-17 -1.48373193e-16
 -6.59436414e-17  8.24295517e-17  9.89154621e-17  8.24295517e-17
 -6.59436414e-17 -9.89154621e-17]

Média do teste:
[3.55755878 3.55790476 3.55863901 3.55894277 3.55950902 3.56010089
 3.56136282 3.56243112 3.59444073 1.01647845 1.01585435 1.01549825
 1.01514867 1.01509049 1.01516608 1.01552476 1.01564652 1.02757436]

In [130]:
print("Desvio padrão do treino:")
print(X_treino_escalado.std(axis=0))

print("\nDesvio padrão do teste:")
print(X_teste_escalado.std(axis=0))

Desvio padrão do treino:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Desvio padrão do teste:
[0.67409906 0.67918486 0.68388995 0.68890802 0.69370667 0.69846785
 0.70269566 0.70706508 0.69279134 0.73574798 0.73579215 0.73569257
 0.735612   0.73540991 0.73516404 0.73484923 0.73460235 0.71526987]

In [131]:
# Variação percentual diária do Bitcoin
dados["BTC_Variacao"] = dados["BTC_Close"].pct_change()

# Variação percentual diária do Ethereum
dados["ETH_Variacao"] = dados["ETH_Close"].pct_change()

In [133]:
dados[["BTC_Close", "BTC_Variacao", "ETH_Close", "ETH_Variacao"]].head(10)

               BTC_Close  BTC_Variacao   ETH_Close  ETH_Variacao
Date
2020-02-06   9729.801758           NaN  212.339081           NaN
2020-02-07   9795.943359      0.006798  222.726059      0.048917
2020-02-08   9865.119141      0.007062  223.146515      0.001888
2020-02-09  10116.673828      0.025499  228.578568      0.024343
2020-02-10   9856.611328     -0.025706  223.522705     -0.022119
2020-02-11  10208.236328      0.035674  235.851196      0.055155
2020-02-12  10326.054688      0.011541  265.406128      0.125312
2020-02-13  10214.379883     -0.010815  268.099243      0.010147
2020-02-14  10312.116211      0.009569  284.217499      0.060120
2020-02-15   9889.424805     -0.040990  264.728577     -0.068570